name: Push Production Docker Image to Private Registry

on:
  push:
    branches:
      - pingbeen

jobs:
  ci:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@master

      - name: Docker Production Build & Push Action ğŸ‘
        uses: mr-smithers-excellent/docker-build-push@v5.6
        with:
          image: pingbeen/uptime-kuma
          registry: docker.io
          dockerfile: docker/Dockerfile.prod
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
